namespace DunGym_Quest
{
    partial class Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
            label1 = new Label();
            panel1 = new Panel();
            userbtn = new SiticoneNetCoreUI.SiticoneButton();
            dashboardbtn = new SiticoneNetCoreUI.SiticoneButton();
            progressbtn = new SiticoneNetCoreUI.SiticoneButton();
            logoutbtn = new SiticoneNetCoreUI.SiticoneButton();
            achievementbtn = new SiticoneNetCoreUI.SiticoneButton();
            bmibtn = new SiticoneNetCoreUI.SiticoneButton();
            leaderboardbtn = new SiticoneNetCoreUI.SiticoneButton();
            exercisebtn = new SiticoneNetCoreUI.SiticoneButton();
            siticonePictureBox3 = new SiticoneNetCoreUI.SiticonePictureBox();
            PanelMain = new SiticoneNetCoreUI.SiticonePanel();
            panel1.SuspendLayout();
            SuspendLayout();
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.BackColor = Color.Transparent;
            label1.Font = new Font("Matura MT Script Capitals", 15.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.Black;
            label1.Location = new Point(5, 71);
            label1.Name = "label1";
            label1.Size = new Size(227, 36);
            label1.TabIndex = 3;
            label1.Text = "DunGym Quest";
            // 
            // panel1
            // 
            panel1.BackColor = Color.FromArgb(255, 193, 94);
            panel1.Controls.Add(userbtn);
            panel1.Controls.Add(dashboardbtn);
            panel1.Controls.Add(progressbtn);
            panel1.Controls.Add(logoutbtn);
            panel1.Controls.Add(label1);
            panel1.Controls.Add(achievementbtn);
            panel1.Controls.Add(bmibtn);
            panel1.Controls.Add(leaderboardbtn);
            panel1.Controls.Add(exercisebtn);
            panel1.Controls.Add(siticonePictureBox3);
            panel1.Dock = DockStyle.Left;
            panel1.Location = new Point(0, 0);
            panel1.Margin = new Padding(3, 4, 3, 4);
            panel1.Name = "panel1";
            panel1.Size = new Size(241, 683);
            panel1.TabIndex = 4;
            // 
            // userbtn
            // 
            userbtn.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            userbtn.AccessibleName = "User Settings";
            userbtn.AutoSizeBasedOnText = false;
            userbtn.BackColor = Color.Transparent;
            userbtn.BadgeBackColor = Color.Red;
            userbtn.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            userbtn.BadgeValue = 0;
            userbtn.BadgeValueForeColor = Color.White;
            userbtn.BorderColor = Color.Transparent;
            userbtn.BorderWidth = 2;
            userbtn.ButtonBackColor = Color.Transparent;
            userbtn.ButtonImage = Properties.Resources.user;
            userbtn.CanBeep = true;
            userbtn.CanGlow = false;
            userbtn.CanShake = true;
            userbtn.ContextMenuStripEx = null;
            userbtn.CornerRadiusBottomLeft = 0;
            userbtn.CornerRadiusBottomRight = 0;
            userbtn.CornerRadiusTopLeft = 0;
            userbtn.CornerRadiusTopRight = 0;
            userbtn.CustomCursor = Cursors.Default;
            userbtn.DisabledTextColor = Color.FromArgb(150, 150, 150);
            userbtn.EnableLongPress = false;
            userbtn.EnablePressAnimation = true;
            userbtn.EnableRippleEffect = true;
            userbtn.EnableShadow = false;
            userbtn.EnableTextWrapping = false;
            userbtn.Font = new Font("Lucida Bright", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            userbtn.ForeColor = Color.Transparent;
            userbtn.GlowColor = Color.FromArgb(100, 255, 255, 255);
            userbtn.GlowIntensity = 100;
            userbtn.GlowRadius = 20F;
            userbtn.GradientBackground = false;
            userbtn.GradientColor = Color.Transparent;
            userbtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            userbtn.HintText = null;
            userbtn.HoverBackColor = Color.FromArgb(204, 88, 3);
            userbtn.HoverFontStyle = FontStyle.Regular;
            userbtn.HoverTextColor = Color.White;
            userbtn.HoverTransitionDuration = 250;
            userbtn.ImageAlign = ContentAlignment.MiddleLeft;
            userbtn.ImagePadding = 5;
            userbtn.ImageSize = new Size(35, 35);
            userbtn.IsRadial = false;
            userbtn.IsReadOnly = false;
            userbtn.IsToggleButton = false;
            userbtn.IsToggled = false;
            userbtn.Location = new Point(0, 498);
            userbtn.LongPressDurationMS = 1000;
            userbtn.Margin = new Padding(3, 4, 3, 4);
            userbtn.Name = "userbtn";
            userbtn.NormalFontStyle = FontStyle.Regular;
            userbtn.ParticleColor = Color.FromArgb(200, 200, 200);
            userbtn.ParticleCount = 15;
            userbtn.PressAnimationScale = 0.97F;
            userbtn.PressedBackColor = Color.FromArgb(247, 147, 76);
            userbtn.PressedFontStyle = FontStyle.Regular;
            userbtn.PressTransitionDuration = 150;
            userbtn.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            userbtn.RippleColor = Color.FromArgb(255, 255, 255);
            userbtn.RippleOpacity = 0.3F;
            userbtn.RippleRadiusMultiplier = 0.6F;
            userbtn.ShadowBlur = 5;
            userbtn.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            userbtn.ShadowOffset = new Point(2, 2);
            userbtn.ShakeDuration = 500;
            userbtn.ShakeIntensity = 5;
            userbtn.Size = new Size(242, 55);
            userbtn.TabIndex = 23;
            userbtn.Text = "User Settings";
            userbtn.TextAlign = ContentAlignment.MiddleCenter;
            userbtn.TextColor = Color.Black;
            userbtn.TooltipText = null;
            userbtn.UseAdvancedRendering = true;
            userbtn.UseParticles = false;
            userbtn.Click += userbtn_Click;
            // 
            // dashboardbtn
            // 
            dashboardbtn.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            dashboardbtn.AccessibleName = "Dashboard";
            dashboardbtn.AutoSizeBasedOnText = false;
            dashboardbtn.BackColor = Color.Transparent;
            dashboardbtn.BadgeBackColor = Color.Red;
            dashboardbtn.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            dashboardbtn.BadgeValue = 0;
            dashboardbtn.BadgeValueForeColor = Color.White;
            dashboardbtn.BorderColor = Color.Transparent;
            dashboardbtn.BorderWidth = 2;
            dashboardbtn.ButtonBackColor = Color.Transparent;
            dashboardbtn.ButtonImage = Properties.Resources.home;
            dashboardbtn.CanBeep = true;
            dashboardbtn.CanGlow = false;
            dashboardbtn.CanShake = true;
            dashboardbtn.ContextMenuStripEx = null;
            dashboardbtn.CornerRadiusBottomLeft = 0;
            dashboardbtn.CornerRadiusBottomRight = 0;
            dashboardbtn.CornerRadiusTopLeft = 0;
            dashboardbtn.CornerRadiusTopRight = 0;
            dashboardbtn.CustomCursor = Cursors.Default;
            dashboardbtn.DisabledTextColor = Color.FromArgb(150, 150, 150);
            dashboardbtn.EnableLongPress = false;
            dashboardbtn.EnablePressAnimation = true;
            dashboardbtn.EnableRippleEffect = true;
            dashboardbtn.EnableShadow = false;
            dashboardbtn.EnableTextWrapping = false;
            dashboardbtn.Font = new Font("Lucida Bright", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            dashboardbtn.ForeColor = Color.Transparent;
            dashboardbtn.GlowColor = Color.FromArgb(100, 255, 255, 255);
            dashboardbtn.GlowIntensity = 100;
            dashboardbtn.GlowRadius = 20F;
            dashboardbtn.GradientBackground = false;
            dashboardbtn.GradientColor = Color.Transparent;
            dashboardbtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            dashboardbtn.HintText = null;
            dashboardbtn.HoverBackColor = Color.FromArgb(204, 88, 3);
            dashboardbtn.HoverFontStyle = FontStyle.Regular;
            dashboardbtn.HoverTextColor = Color.White;
            dashboardbtn.HoverTransitionDuration = 250;
            dashboardbtn.ImageAlign = ContentAlignment.MiddleLeft;
            dashboardbtn.ImagePadding = 5;
            dashboardbtn.ImageSize = new Size(35, 35);
            dashboardbtn.IsRadial = false;
            dashboardbtn.IsReadOnly = false;
            dashboardbtn.IsToggleButton = false;
            dashboardbtn.IsToggled = false;
            dashboardbtn.Location = new Point(-1, 131);
            dashboardbtn.LongPressDurationMS = 1000;
            dashboardbtn.Margin = new Padding(3, 4, 3, 4);
            dashboardbtn.Name = "dashboardbtn";
            dashboardbtn.NormalFontStyle = FontStyle.Regular;
            dashboardbtn.ParticleColor = Color.FromArgb(200, 200, 200);
            dashboardbtn.ParticleCount = 15;
            dashboardbtn.PressAnimationScale = 0.97F;
            dashboardbtn.PressedBackColor = Color.FromArgb(247, 147, 76);
            dashboardbtn.PressedFontStyle = FontStyle.Regular;
            dashboardbtn.PressTransitionDuration = 150;
            dashboardbtn.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            dashboardbtn.RippleColor = Color.FromArgb(255, 255, 255);
            dashboardbtn.RippleOpacity = 0.3F;
            dashboardbtn.RippleRadiusMultiplier = 0.6F;
            dashboardbtn.ShadowBlur = 5;
            dashboardbtn.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            dashboardbtn.ShadowOffset = new Point(2, 2);
            dashboardbtn.ShakeDuration = 500;
            dashboardbtn.ShakeIntensity = 5;
            dashboardbtn.Size = new Size(242, 67);
            dashboardbtn.TabIndex = 22;
            dashboardbtn.Text = "Dashboard";
            dashboardbtn.TextAlign = ContentAlignment.MiddleCenter;
            dashboardbtn.TextColor = Color.Black;
            dashboardbtn.TooltipText = null;
            dashboardbtn.UseAdvancedRendering = true;
            dashboardbtn.UseParticles = false;
            dashboardbtn.Click += dashboardbtn_Click;
            // 
            // progressbtn
            // 
            progressbtn.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            progressbtn.AccessibleName = "Progress";
            progressbtn.AutoSizeBasedOnText = false;
            progressbtn.BackColor = Color.Transparent;
            progressbtn.BadgeBackColor = Color.Red;
            progressbtn.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            progressbtn.BadgeValue = 0;
            progressbtn.BadgeValueForeColor = Color.White;
            progressbtn.BorderColor = Color.Transparent;
            progressbtn.BorderWidth = 2;
            progressbtn.ButtonBackColor = Color.Transparent;
            progressbtn.ButtonImage = Properties.Resources.progress;
            progressbtn.CanBeep = true;
            progressbtn.CanGlow = false;
            progressbtn.CanShake = true;
            progressbtn.ContextMenuStripEx = null;
            progressbtn.CornerRadiusBottomLeft = 0;
            progressbtn.CornerRadiusBottomRight = 0;
            progressbtn.CornerRadiusTopLeft = 0;
            progressbtn.CornerRadiusTopRight = 0;
            progressbtn.CustomCursor = Cursors.Default;
            progressbtn.DisabledTextColor = Color.FromArgb(150, 150, 150);
            progressbtn.EnableLongPress = false;
            progressbtn.EnablePressAnimation = true;
            progressbtn.EnableRippleEffect = true;
            progressbtn.EnableShadow = false;
            progressbtn.EnableTextWrapping = false;
            progressbtn.Font = new Font("Lucida Bright", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            progressbtn.ForeColor = Color.Transparent;
            progressbtn.GlowColor = Color.FromArgb(100, 255, 255, 255);
            progressbtn.GlowIntensity = 100;
            progressbtn.GlowRadius = 20F;
            progressbtn.GradientBackground = false;
            progressbtn.GradientColor = Color.Transparent;
            progressbtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            progressbtn.HintText = null;
            progressbtn.HoverBackColor = Color.FromArgb(204, 88, 3);
            progressbtn.HoverFontStyle = FontStyle.Regular;
            progressbtn.HoverTextColor = Color.White;
            progressbtn.HoverTransitionDuration = 250;
            progressbtn.ImageAlign = ContentAlignment.MiddleLeft;
            progressbtn.ImagePadding = 5;
            progressbtn.ImageSize = new Size(35, 35);
            progressbtn.IsRadial = false;
            progressbtn.IsReadOnly = false;
            progressbtn.IsToggleButton = false;
            progressbtn.IsToggled = false;
            progressbtn.Location = new Point(-1, 434);
            progressbtn.LongPressDurationMS = 1000;
            progressbtn.Margin = new Padding(3, 4, 3, 4);
            progressbtn.Name = "progressbtn";
            progressbtn.NormalFontStyle = FontStyle.Regular;
            progressbtn.ParticleColor = Color.FromArgb(200, 200, 200);
            progressbtn.ParticleCount = 15;
            progressbtn.PressAnimationScale = 0.97F;
            progressbtn.PressedBackColor = Color.FromArgb(247, 147, 76);
            progressbtn.PressedFontStyle = FontStyle.Regular;
            progressbtn.PressTransitionDuration = 150;
            progressbtn.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            progressbtn.RippleColor = Color.FromArgb(255, 255, 255);
            progressbtn.RippleOpacity = 0.3F;
            progressbtn.RippleRadiusMultiplier = 0.6F;
            progressbtn.ShadowBlur = 5;
            progressbtn.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            progressbtn.ShadowOffset = new Point(2, 2);
            progressbtn.ShakeDuration = 500;
            progressbtn.ShakeIntensity = 5;
            progressbtn.Size = new Size(242, 67);
            progressbtn.TabIndex = 20;
            progressbtn.Text = "Progress";
            progressbtn.TextAlign = ContentAlignment.MiddleCenter;
            progressbtn.TextColor = Color.Black;
            progressbtn.TooltipText = null;
            progressbtn.UseAdvancedRendering = true;
            progressbtn.UseParticles = false;
            progressbtn.Click += progressbtn_Click;
            // 
            // logoutbtn
            // 
            logoutbtn.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            logoutbtn.AccessibleName = "Logout";
            logoutbtn.AutoSizeBasedOnText = false;
            logoutbtn.BackColor = Color.Transparent;
            logoutbtn.BadgeBackColor = Color.Red;
            logoutbtn.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            logoutbtn.BadgeValue = 0;
            logoutbtn.BadgeValueForeColor = Color.White;
            logoutbtn.BorderColor = Color.Transparent;
            logoutbtn.BorderWidth = 2;
            logoutbtn.ButtonBackColor = Color.Transparent;
            logoutbtn.ButtonImage = Properties.Resources.logout;
            logoutbtn.CanBeep = true;
            logoutbtn.CanGlow = false;
            logoutbtn.CanShake = true;
            logoutbtn.ContextMenuStripEx = null;
            logoutbtn.CornerRadiusBottomLeft = 0;
            logoutbtn.CornerRadiusBottomRight = 0;
            logoutbtn.CornerRadiusTopLeft = 0;
            logoutbtn.CornerRadiusTopRight = 0;
            logoutbtn.CustomCursor = Cursors.Default;
            logoutbtn.DisabledTextColor = Color.FromArgb(150, 150, 150);
            logoutbtn.EnableLongPress = false;
            logoutbtn.EnablePressAnimation = true;
            logoutbtn.EnableRippleEffect = true;
            logoutbtn.EnableShadow = false;
            logoutbtn.EnableTextWrapping = false;
            logoutbtn.Font = new Font("Lucida Bright", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            logoutbtn.ForeColor = Color.Transparent;
            logoutbtn.GlowColor = Color.FromArgb(100, 255, 255, 255);
            logoutbtn.GlowIntensity = 100;
            logoutbtn.GlowRadius = 20F;
            logoutbtn.GradientBackground = false;
            logoutbtn.GradientColor = Color.Transparent;
            logoutbtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            logoutbtn.HintText = null;
            logoutbtn.HoverBackColor = Color.FromArgb(204, 88, 3);
            logoutbtn.HoverFontStyle = FontStyle.Regular;
            logoutbtn.HoverTextColor = Color.White;
            logoutbtn.HoverTransitionDuration = 250;
            logoutbtn.ImageAlign = ContentAlignment.MiddleLeft;
            logoutbtn.ImagePadding = 5;
            logoutbtn.ImageSize = new Size(25, 25);
            logoutbtn.IsRadial = false;
            logoutbtn.IsReadOnly = false;
            logoutbtn.IsToggleButton = false;
            logoutbtn.IsToggled = false;
            logoutbtn.Location = new Point(-3, 616);
            logoutbtn.LongPressDurationMS = 1000;
            logoutbtn.Margin = new Padding(3, 4, 3, 4);
            logoutbtn.Name = "logoutbtn";
            logoutbtn.NormalFontStyle = FontStyle.Regular;
            logoutbtn.ParticleColor = Color.FromArgb(200, 200, 200);
            logoutbtn.ParticleCount = 15;
            logoutbtn.PressAnimationScale = 0.97F;
            logoutbtn.PressedBackColor = Color.FromArgb(247, 147, 76);
            logoutbtn.PressedFontStyle = FontStyle.Regular;
            logoutbtn.PressTransitionDuration = 150;
            logoutbtn.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            logoutbtn.RippleColor = Color.FromArgb(255, 255, 255);
            logoutbtn.RippleOpacity = 0.3F;
            logoutbtn.RippleRadiusMultiplier = 0.6F;
            logoutbtn.ShadowBlur = 5;
            logoutbtn.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            logoutbtn.ShadowOffset = new Point(2, 2);
            logoutbtn.ShakeDuration = 500;
            logoutbtn.ShakeIntensity = 5;
            logoutbtn.Size = new Size(242, 67);
            logoutbtn.TabIndex = 19;
            logoutbtn.Text = "Logout";
            logoutbtn.TextAlign = ContentAlignment.MiddleLeft;
            logoutbtn.TextColor = Color.Black;
            logoutbtn.TooltipText = null;
            logoutbtn.UseAdvancedRendering = true;
            logoutbtn.UseParticles = false;
            logoutbtn.Click += logoutbtn_Click;
            // 
            // achievementbtn
            // 
            achievementbtn.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            achievementbtn.AccessibleName = "Achievements";
            achievementbtn.AutoSizeBasedOnText = false;
            achievementbtn.BackColor = Color.Transparent;
            achievementbtn.BadgeBackColor = Color.Red;
            achievementbtn.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            achievementbtn.BadgeValue = 0;
            achievementbtn.BadgeValueForeColor = Color.White;
            achievementbtn.BorderColor = Color.Transparent;
            achievementbtn.BorderWidth = 2;
            achievementbtn.ButtonBackColor = Color.Transparent;
            achievementbtn.ButtonImage = Properties.Resources.achievement;
            achievementbtn.CanBeep = true;
            achievementbtn.CanGlow = false;
            achievementbtn.CanShake = true;
            achievementbtn.ContextMenuStripEx = null;
            achievementbtn.CornerRadiusBottomLeft = 0;
            achievementbtn.CornerRadiusBottomRight = 0;
            achievementbtn.CornerRadiusTopLeft = 0;
            achievementbtn.CornerRadiusTopRight = 0;
            achievementbtn.CustomCursor = Cursors.Default;
            achievementbtn.DisabledTextColor = Color.FromArgb(150, 150, 150);
            achievementbtn.EnableLongPress = false;
            achievementbtn.EnablePressAnimation = true;
            achievementbtn.EnableRippleEffect = true;
            achievementbtn.EnableShadow = false;
            achievementbtn.EnableTextWrapping = false;
            achievementbtn.Font = new Font("Lucida Bright", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            achievementbtn.ForeColor = Color.Transparent;
            achievementbtn.GlowColor = Color.FromArgb(100, 255, 255, 255);
            achievementbtn.GlowIntensity = 100;
            achievementbtn.GlowRadius = 20F;
            achievementbtn.GradientBackground = false;
            achievementbtn.GradientColor = Color.Transparent;
            achievementbtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            achievementbtn.HintText = null;
            achievementbtn.HoverBackColor = Color.FromArgb(204, 88, 3);
            achievementbtn.HoverFontStyle = FontStyle.Regular;
            achievementbtn.HoverTextColor = Color.White;
            achievementbtn.HoverTransitionDuration = 250;
            achievementbtn.ImageAlign = ContentAlignment.MiddleLeft;
            achievementbtn.ImagePadding = 5;
            achievementbtn.ImageSize = new Size(35, 35);
            achievementbtn.IsRadial = false;
            achievementbtn.IsReadOnly = false;
            achievementbtn.IsToggleButton = false;
            achievementbtn.IsToggled = false;
            achievementbtn.Location = new Point(-1, 375);
            achievementbtn.LongPressDurationMS = 1000;
            achievementbtn.Margin = new Padding(3, 4, 3, 4);
            achievementbtn.Name = "achievementbtn";
            achievementbtn.NormalFontStyle = FontStyle.Regular;
            achievementbtn.ParticleColor = Color.FromArgb(200, 200, 200);
            achievementbtn.ParticleCount = 15;
            achievementbtn.PressAnimationScale = 0.97F;
            achievementbtn.PressedBackColor = Color.FromArgb(247, 147, 76);
            achievementbtn.PressedFontStyle = FontStyle.Regular;
            achievementbtn.PressTransitionDuration = 150;
            achievementbtn.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            achievementbtn.RippleColor = Color.FromArgb(255, 255, 255);
            achievementbtn.RippleOpacity = 0.3F;
            achievementbtn.RippleRadiusMultiplier = 0.6F;
            achievementbtn.ShadowBlur = 5;
            achievementbtn.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            achievementbtn.ShadowOffset = new Point(2, 2);
            achievementbtn.ShakeDuration = 500;
            achievementbtn.ShakeIntensity = 5;
            achievementbtn.Size = new Size(242, 67);
            achievementbtn.TabIndex = 17;
            achievementbtn.Text = "Achievements";
            achievementbtn.TextAlign = ContentAlignment.MiddleCenter;
            achievementbtn.TextColor = Color.Black;
            achievementbtn.TooltipText = null;
            achievementbtn.UseAdvancedRendering = true;
            achievementbtn.UseParticles = false;
            achievementbtn.Click += achievementbtn_Click;
            // 
            // bmibtn
            // 
            bmibtn.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            bmibtn.AccessibleName = "BMI Calculator";
            bmibtn.AutoSizeBasedOnText = false;
            bmibtn.BackColor = Color.Transparent;
            bmibtn.BadgeBackColor = Color.Red;
            bmibtn.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            bmibtn.BadgeValue = 0;
            bmibtn.BadgeValueForeColor = Color.White;
            bmibtn.BorderColor = Color.Transparent;
            bmibtn.BorderWidth = 2;
            bmibtn.ButtonBackColor = Color.Transparent;
            bmibtn.ButtonImage = Properties.Resources.bmi2;
            bmibtn.CanBeep = true;
            bmibtn.CanGlow = false;
            bmibtn.CanShake = true;
            bmibtn.ContextMenuStripEx = null;
            bmibtn.CornerRadiusBottomLeft = 0;
            bmibtn.CornerRadiusBottomRight = 0;
            bmibtn.CornerRadiusTopLeft = 0;
            bmibtn.CornerRadiusTopRight = 0;
            bmibtn.CustomCursor = Cursors.Default;
            bmibtn.DisabledTextColor = Color.FromArgb(150, 150, 150);
            bmibtn.EnableLongPress = false;
            bmibtn.EnablePressAnimation = true;
            bmibtn.EnableRippleEffect = true;
            bmibtn.EnableShadow = false;
            bmibtn.EnableTextWrapping = false;
            bmibtn.Font = new Font("Lucida Bright", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bmibtn.ForeColor = Color.Transparent;
            bmibtn.GlowColor = Color.FromArgb(100, 255, 255, 255);
            bmibtn.GlowIntensity = 100;
            bmibtn.GlowRadius = 20F;
            bmibtn.GradientBackground = false;
            bmibtn.GradientColor = Color.Transparent;
            bmibtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            bmibtn.HintText = null;
            bmibtn.HoverBackColor = Color.FromArgb(204, 88, 3);
            bmibtn.HoverFontStyle = FontStyle.Regular;
            bmibtn.HoverTextColor = Color.White;
            bmibtn.HoverTransitionDuration = 250;
            bmibtn.ImageAlign = ContentAlignment.MiddleLeft;
            bmibtn.ImagePadding = 5;
            bmibtn.ImageSize = new Size(35, 35);
            bmibtn.IsRadial = false;
            bmibtn.IsReadOnly = false;
            bmibtn.IsToggleButton = false;
            bmibtn.IsToggled = false;
            bmibtn.Location = new Point(-1, 195);
            bmibtn.LongPressDurationMS = 1000;
            bmibtn.Margin = new Padding(3, 4, 3, 4);
            bmibtn.Name = "bmibtn";
            bmibtn.NormalFontStyle = FontStyle.Regular;
            bmibtn.ParticleColor = Color.FromArgb(200, 200, 200);
            bmibtn.ParticleCount = 15;
            bmibtn.PressAnimationScale = 0.97F;
            bmibtn.PressedBackColor = Color.FromArgb(247, 147, 76);
            bmibtn.PressedFontStyle = FontStyle.Regular;
            bmibtn.PressTransitionDuration = 150;
            bmibtn.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            bmibtn.RippleColor = Color.FromArgb(255, 255, 255);
            bmibtn.RippleOpacity = 0.3F;
            bmibtn.RippleRadiusMultiplier = 0.6F;
            bmibtn.ShadowBlur = 5;
            bmibtn.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            bmibtn.ShadowOffset = new Point(2, 2);
            bmibtn.ShakeDuration = 500;
            bmibtn.ShakeIntensity = 5;
            bmibtn.Size = new Size(242, 67);
            bmibtn.TabIndex = 18;
            bmibtn.Text = "BMI Calculator";
            bmibtn.TextAlign = ContentAlignment.MiddleCenter;
            bmibtn.TextColor = Color.Black;
            bmibtn.TooltipText = null;
            bmibtn.UseAdvancedRendering = true;
            bmibtn.UseParticles = false;
            bmibtn.Click += bmibtn_Click;
            // 
            // leaderboardbtn
            // 
            leaderboardbtn.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            leaderboardbtn.AccessibleName = "Leaderboard";
            leaderboardbtn.AutoSizeBasedOnText = false;
            leaderboardbtn.BackColor = Color.Transparent;
            leaderboardbtn.BadgeBackColor = Color.Red;
            leaderboardbtn.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            leaderboardbtn.BadgeValue = 0;
            leaderboardbtn.BadgeValueForeColor = Color.White;
            leaderboardbtn.BorderColor = Color.Transparent;
            leaderboardbtn.BorderWidth = 2;
            leaderboardbtn.ButtonBackColor = Color.Transparent;
            leaderboardbtn.ButtonImage = (Image)resources.GetObject("leaderboardbtn.ButtonImage");
            leaderboardbtn.CanBeep = true;
            leaderboardbtn.CanGlow = false;
            leaderboardbtn.CanShake = true;
            leaderboardbtn.ContextMenuStripEx = null;
            leaderboardbtn.CornerRadiusBottomLeft = 0;
            leaderboardbtn.CornerRadiusBottomRight = 0;
            leaderboardbtn.CornerRadiusTopLeft = 0;
            leaderboardbtn.CornerRadiusTopRight = 0;
            leaderboardbtn.CustomCursor = Cursors.Default;
            leaderboardbtn.DisabledTextColor = Color.FromArgb(150, 150, 150);
            leaderboardbtn.EnableLongPress = false;
            leaderboardbtn.EnablePressAnimation = true;
            leaderboardbtn.EnableRippleEffect = true;
            leaderboardbtn.EnableShadow = false;
            leaderboardbtn.EnableTextWrapping = false;
            leaderboardbtn.Font = new Font("Lucida Bright", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            leaderboardbtn.ForeColor = Color.Transparent;
            leaderboardbtn.GlowColor = Color.FromArgb(100, 255, 255, 255);
            leaderboardbtn.GlowIntensity = 100;
            leaderboardbtn.GlowRadius = 20F;
            leaderboardbtn.GradientBackground = false;
            leaderboardbtn.GradientColor = Color.Transparent;
            leaderboardbtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            leaderboardbtn.HintText = null;
            leaderboardbtn.HoverBackColor = Color.FromArgb(204, 88, 3);
            leaderboardbtn.HoverFontStyle = FontStyle.Regular;
            leaderboardbtn.HoverTextColor = Color.White;
            leaderboardbtn.HoverTransitionDuration = 250;
            leaderboardbtn.ImageAlign = ContentAlignment.MiddleLeft;
            leaderboardbtn.ImagePadding = 5;
            leaderboardbtn.ImageSize = new Size(35, 35);
            leaderboardbtn.IsRadial = false;
            leaderboardbtn.IsReadOnly = false;
            leaderboardbtn.IsToggleButton = false;
            leaderboardbtn.IsToggled = false;
            leaderboardbtn.Location = new Point(-1, 314);
            leaderboardbtn.LongPressDurationMS = 1000;
            leaderboardbtn.Margin = new Padding(3, 4, 3, 4);
            leaderboardbtn.Name = "leaderboardbtn";
            leaderboardbtn.NormalFontStyle = FontStyle.Regular;
            leaderboardbtn.ParticleColor = Color.FromArgb(200, 200, 200);
            leaderboardbtn.ParticleCount = 15;
            leaderboardbtn.PressAnimationScale = 0.97F;
            leaderboardbtn.PressedBackColor = Color.FromArgb(247, 147, 76);
            leaderboardbtn.PressedFontStyle = FontStyle.Regular;
            leaderboardbtn.PressTransitionDuration = 150;
            leaderboardbtn.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            leaderboardbtn.RippleColor = Color.FromArgb(255, 255, 255);
            leaderboardbtn.RippleOpacity = 0.3F;
            leaderboardbtn.RippleRadiusMultiplier = 0.6F;
            leaderboardbtn.ShadowBlur = 5;
            leaderboardbtn.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            leaderboardbtn.ShadowOffset = new Point(2, 2);
            leaderboardbtn.ShakeDuration = 500;
            leaderboardbtn.ShakeIntensity = 5;
            leaderboardbtn.Size = new Size(242, 67);
            leaderboardbtn.TabIndex = 17;
            leaderboardbtn.Text = "Leaderboard";
            leaderboardbtn.TextAlign = ContentAlignment.MiddleCenter;
            leaderboardbtn.TextColor = Color.Black;
            leaderboardbtn.TooltipText = null;
            leaderboardbtn.UseAdvancedRendering = true;
            leaderboardbtn.UseParticles = false;
            leaderboardbtn.Click += leaderboardbtn_Click;
            // 
            // exercisebtn
            // 
            exercisebtn.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            exercisebtn.AccessibleName = "Exercises";
            exercisebtn.AutoSizeBasedOnText = false;
            exercisebtn.BackColor = Color.Transparent;
            exercisebtn.BadgeBackColor = Color.Red;
            exercisebtn.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            exercisebtn.BadgeValue = 0;
            exercisebtn.BadgeValueForeColor = Color.White;
            exercisebtn.BorderColor = Color.Transparent;
            exercisebtn.BorderWidth = 2;
            exercisebtn.ButtonBackColor = Color.Transparent;
            exercisebtn.ButtonImage = Properties.Resources._1;
            exercisebtn.CanBeep = true;
            exercisebtn.CanGlow = false;
            exercisebtn.CanShake = true;
            exercisebtn.ContextMenuStripEx = null;
            exercisebtn.CornerRadiusBottomLeft = 0;
            exercisebtn.CornerRadiusBottomRight = 0;
            exercisebtn.CornerRadiusTopLeft = 0;
            exercisebtn.CornerRadiusTopRight = 0;
            exercisebtn.CustomCursor = Cursors.Default;
            exercisebtn.DisabledTextColor = Color.FromArgb(150, 150, 150);
            exercisebtn.EnableLongPress = false;
            exercisebtn.EnablePressAnimation = true;
            exercisebtn.EnableRippleEffect = true;
            exercisebtn.EnableShadow = false;
            exercisebtn.EnableTextWrapping = false;
            exercisebtn.Font = new Font("Lucida Bright", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            exercisebtn.ForeColor = Color.Transparent;
            exercisebtn.GlowColor = Color.FromArgb(100, 255, 255, 255);
            exercisebtn.GlowIntensity = 100;
            exercisebtn.GlowRadius = 20F;
            exercisebtn.GradientBackground = false;
            exercisebtn.GradientColor = Color.Transparent;
            exercisebtn.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            exercisebtn.HintText = null;
            exercisebtn.HoverBackColor = Color.FromArgb(204, 88, 3);
            exercisebtn.HoverFontStyle = FontStyle.Regular;
            exercisebtn.HoverTextColor = Color.White;
            exercisebtn.HoverTransitionDuration = 250;
            exercisebtn.ImageAlign = ContentAlignment.MiddleLeft;
            exercisebtn.ImagePadding = 5;
            exercisebtn.ImageSize = new Size(35, 35);
            exercisebtn.IsRadial = false;
            exercisebtn.IsReadOnly = false;
            exercisebtn.IsToggleButton = false;
            exercisebtn.IsToggled = false;
            exercisebtn.Location = new Point(-1, 255);
            exercisebtn.LongPressDurationMS = 1000;
            exercisebtn.Margin = new Padding(3, 4, 3, 4);
            exercisebtn.Name = "exercisebtn";
            exercisebtn.NormalFontStyle = FontStyle.Regular;
            exercisebtn.ParticleColor = Color.FromArgb(200, 200, 200);
            exercisebtn.ParticleCount = 15;
            exercisebtn.PressAnimationScale = 0.97F;
            exercisebtn.PressedBackColor = Color.FromArgb(247, 147, 76);
            exercisebtn.PressedFontStyle = FontStyle.Regular;
            exercisebtn.PressTransitionDuration = 150;
            exercisebtn.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            exercisebtn.RippleColor = Color.FromArgb(255, 255, 255);
            exercisebtn.RippleOpacity = 0.3F;
            exercisebtn.RippleRadiusMultiplier = 0.6F;
            exercisebtn.ShadowBlur = 5;
            exercisebtn.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            exercisebtn.ShadowOffset = new Point(2, 2);
            exercisebtn.ShakeDuration = 500;
            exercisebtn.ShakeIntensity = 5;
            exercisebtn.Size = new Size(242, 67);
            exercisebtn.TabIndex = 16;
            exercisebtn.Text = "Exercises";
            exercisebtn.TextAlign = ContentAlignment.MiddleCenter;
            exercisebtn.TextColor = Color.Black;
            exercisebtn.TooltipText = null;
            exercisebtn.UseAdvancedRendering = true;
            exercisebtn.UseParticles = false;
            exercisebtn.Click += exercisebtn_Click;
            // 
            // siticonePictureBox3
            // 
            siticonePictureBox3.BackColor = Color.Transparent;
            siticonePictureBox3.BackgroundImage = Properties.Resources._2;
            siticonePictureBox3.BackgroundImageLayout = ImageLayout.Stretch;
            siticonePictureBox3.BorderColor = Color.Black;
            siticonePictureBox3.BorderWidth = 1;
            siticonePictureBox3.Brightness = 1F;
            siticonePictureBox3.Contrast = 1F;
            siticonePictureBox3.CornerRadius = 0;
            siticonePictureBox3.DraggingSpeed = 3.15F;
            siticonePictureBox3.EnableAsyncLoading = false;
            siticonePictureBox3.EnableCaching = false;
            siticonePictureBox3.EnableDragDrop = false;
            siticonePictureBox3.EnableExtendedImageSources = false;
            siticonePictureBox3.EnableFilters = false;
            siticonePictureBox3.EnableFlipping = false;
            siticonePictureBox3.EnableGlow = false;
            siticonePictureBox3.EnableHighDpiSupport = false;
            siticonePictureBox3.EnableMouseInteraction = false;
            siticonePictureBox3.EnablePlaceholder = false;
            siticonePictureBox3.EnableRotation = false;
            siticonePictureBox3.EnableShadow = false;
            siticonePictureBox3.EnableSlideshow = false;
            siticonePictureBox3.FlipHorizontal = false;
            siticonePictureBox3.FlipVertical = false;
            siticonePictureBox3.Grayscale = false;
            siticonePictureBox3.Image = null;
            siticonePictureBox3.ImageOpacity = 1F;
            siticonePictureBox3.Images = (List<Image>)resources.GetObject("siticonePictureBox3.Images");
            siticonePictureBox3.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
            siticonePictureBox3.IsCircular = false;
            siticonePictureBox3.Location = new Point(67, 0);
            siticonePictureBox3.MaintainAspectRatio = true;
            siticonePictureBox3.Margin = new Padding(3, 4, 3, 4);
            siticonePictureBox3.Name = "siticonePictureBox3";
            siticonePictureBox3.PlaceholderImage = null;
            siticonePictureBox3.RotationAngle = 0F;
            siticonePictureBox3.Saturation = 1F;
            siticonePictureBox3.ShowBorder = true;
            siticonePictureBox3.Size = new Size(111, 88);
            siticonePictureBox3.SizeMode = SiticoneNetCoreUI.SiticonePictureBoxSizeMode.Normal;
            siticonePictureBox3.TabIndex = 15;
            siticonePictureBox3.Text = "siticonePictureBox3";
            // 
            // PanelMain
            // 
            PanelMain.AcrylicTintColor = Color.FromArgb(128, 255, 255, 255);
            PanelMain.BackColor = Color.Transparent;
            PanelMain.BorderAlignment = System.Drawing.Drawing2D.PenAlignment.Center;
            PanelMain.BorderDashPattern = null;
            PanelMain.BorderGradientEndColor = Color.Purple;
            PanelMain.BorderGradientStartColor = Color.Blue;
            PanelMain.BorderThickness = 2F;
            PanelMain.CornerRadiusBottomLeft = 10F;
            PanelMain.CornerRadiusBottomRight = 10F;
            PanelMain.CornerRadiusTopLeft = 10F;
            PanelMain.CornerRadiusTopRight = 10F;
            PanelMain.Dock = DockStyle.Right;
            PanelMain.EnableAcrylicEffect = false;
            PanelMain.EnableMicaEffect = false;
            PanelMain.EnableRippleEffect = false;
            PanelMain.FillColor = Color.White;
            PanelMain.GradientColors = new Color[]
    {
    Color.White,
    Color.LightGray,
    Color.Gray
    };
            PanelMain.GradientPositions = new float[]
    {
    0F,
    0.5F,
    1F
    };
            PanelMain.Location = new Point(241, 0);
            PanelMain.Name = "PanelMain";
            PanelMain.PatternStyle = System.Drawing.Drawing2D.HatchStyle.Max;
            PanelMain.RippleAlpha = 50;
            PanelMain.RippleAlphaDecrement = 3;
            PanelMain.RippleColor = Color.FromArgb(50, 255, 255, 255);
            PanelMain.RippleMaxSize = 600F;
            PanelMain.RippleSpeed = 15F;
            PanelMain.ShowBorder = true;
            PanelMain.Size = new Size(768, 683);
            PanelMain.TabIndex = 17;
            PanelMain.TabStop = true;
            PanelMain.UseBorderGradient = false;
            PanelMain.UseMultiGradient = false;
            PanelMain.UsePatternTexture = false;
            PanelMain.UseRadialGradient = false;
            // 
            // Main
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.Cornsilk;
            BackgroundImageLayout = ImageLayout.Stretch;
            ClientSize = new Size(1009, 683);
            Controls.Add(panel1);
            Controls.Add(PanelMain);
            ForeColor = Color.LightGray;
            FormBorderStyle = FormBorderStyle.FixedSingle;
            Margin = new Padding(3, 4, 3, 4);
            Name = "Main";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "s";
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Label label1;
        private Panel panel1;
        private SiticoneNetCoreUI.SiticonePictureBox siticonePictureBox3;
        private SiticoneNetCoreUI.SiticoneButton leaderboardbtn;
        private SiticoneNetCoreUI.SiticoneButton exercisebtn;
        private SiticoneNetCoreUI.SiticoneButton achievementbtn;
        private SiticoneNetCoreUI.SiticoneButton bmibtn;
        private SiticoneNetCoreUI.SiticoneButton logoutbtn;
        private SiticoneNetCoreUI.SiticonePanel siticonePanel3;
        private SiticoneNetCoreUI.SiticoneButton progressbtn;
        private SiticoneNetCoreUI.SiticoneButton dashboardbtn;
        private SiticoneNetCoreUI.SiticonePanel PanelMain;
        private SiticoneNetCoreUI.SiticoneButton userbtn;
    }
}